$font = JetBrainsMono Nerd Font
source = $HOME/.config/hypr/hyprlock-wallpaper.conf

general {
    hide_cursor = true
}

background {
    path = $CYBER_WALLPAPER
    color = rgba(000000ff)
}

label {
    text = $TIME
    color = rgba(eeeeeeff)
    font_size = 48
    font_family = $font
    position = 0, 90
    halign = center
    valign = center
}

input-field {
    size = 320, 58
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.25
    dots_center = true
    outer_color = rgba(ffffffff)
    inner_color = rgba(111111ee)
    font_color = rgba(eeeeeeff)
    fade_on_empty = false
    placeholder_text = <span foreground="##cccccc">Authenticate to unlock</span>
    check_color = rgba(ffffffff)
    fail_color = rgba(aaaaaaff)
    fail_text = <span foreground="##aaaaaa">Incorrect password</span>
    position = 0, -30
    halign = center
    valign = center
}
