$font = JetBrainsMono Nerd Font

general {
    hide_cursor = true
}

background {
    color = rgba(07100bff)
}

label {
    text = $TIME
    color = rgba(b7f7c0ff)
    font_size = 48
    font_family = $font
    position = 0, 90
    halign = center
    valign = center
}

input-field {
    size = 320, 58
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.25
    dots_center = true
    outer_color = rgba(5bd67dff)
    inner_color = rgba(102016ee)
    font_color = rgba(b7f7c0ff)
    fade_on_empty = false
    placeholder_text = <span foreground="##8df0a6">Authenticate to unlock</span>
    check_color = rgba(8df0a6ff)
    fail_color = rgba(f1c66dff)
    fail_text = <span foreground="##f1c66d">Incorrect password</span>
    position = 0, -30
    halign = center
    valign = center
}
