$font = JetBrainsMono Nerd Font
source = $HOME/.config/hypr/hyprlock-wallpaper.conf

general {
    hide_cursor = true
}

background {
    path = $CYBER_WALLPAPER
    color = rgba(080c0fff)
}

label {
    text = $TIME
    color = rgba(e4eaecff)
    font_size = 48
    font_family = $font
    position = 0, 90
    halign = center
    valign = center
}

input-field {
    size = 320, 58
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.25
    dots_center = true
    outer_color = rgba(63b9d2ff)
    inner_color = rgba(11191eee)
    font_color = rgba(e4eaecff)
    fade_on_empty = false
    placeholder_text = <span foreground="##7ed9c2">Authenticate to unlock</span>
    check_color = rgba(7ed9c2ff)
    fail_color = rgba(75bce0ff)
    fail_text = <span foreground="##75bce0">Incorrect password</span>
    position = 0, -30
    halign = center
    valign = center
}
