$font = JetBrainsMono Nerd Font

general {
    hide_cursor = true
}

background {
    color = rgba(0b0f14ff)
}

label {
    text = $TIME
    color = rgba(d7e3f4ff)
    font_size = 48
    font_family = $font
    position = 0, 90
    halign = center
    valign = center
}

input-field {
    size = 320, 58
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.25
    dots_center = true
    outer_color = rgba(8b5cffff)
    inner_color = rgba(131b26ee)
    font_color = rgba(d7e3f4ff)
    fade_on_empty = false
    placeholder_text = <span foreground="##00e5ff">Authenticate to unlock</span>
    check_color = rgba(00e5ffff)
    fail_color = rgba(ff3cafff)
    fail_text = <span foreground="##ff3caf">Incorrect password</span>
    position = 0, -30
    halign = center
    valign = center
}
